### ISSUE TITLE
Jotion이랑 Tution 몇 개 남은 것들

### ISSUE THREAD

**Issue by hyuckkim** [Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum#20]
settings-modal.tsx:
![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/76a2fd73-7890-458b-ac24-d8bffd046b94) ![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/9717987e-4e49-497f-872c-54ee864fc492)

search-command.tsx:
![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/bb558c68-9067-44e7-8bb4-21eb05803be2) ![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/ec46a645-0f8a-485d-a1d6-d2f249cb39ab)

탭 (layout.tsx):
![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/9c393e91-4649-4ff9-a5d6-3ba70062e960) ![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/64761a2f-c3a8-487b-bc77-ddd21f9d09a6)

user-item.tsx:
![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/587c2d92-552a-456b-bdfa-247f458aa216) ![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/53367179/de18a2e0-9c4d-4553-bdeb-6abd393c28d6)

그리고 몇 개 더 있어요

**Comment by seojinJeon** [comment]
![image](https://github.com/Google-Developer-Student-Clubs-TUK/2024-Next.js-project-Daum/assets/127572801/73a8807d-fe49-4aa9-a7f1-9dd34ce33ae2)
